DROP TABLE IF EXISTS book;
CREATE TABLE IF NOT EXISTS book(
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    title VARCHAR(100),
    description VARCHAR(255),
    author VARCHAR(100),
    isbn VARCHAR(20),
    printed INT,
    readalready BIT NOT NULL,
    PRIMARY KEY(id)
) ENGINE = InnoDB;
INSERT INTO book (title, description, author, isbn, printed, readalready) VALUES
    ('Java I/O', 'Java I/O tells you all you need to know about the four main categories of streams and uncovers less known features to help make your I/O operations more efficient.', 'Elliotte Rusty Harold', '1-56592-485-1', 1999, 0),
    ('The Java Handbook', 'After reading this you`ll be amazed that Java really happened.', 'Patrick Naughton, Michael Morrison', '0078821991', 1996, 0),
    ('Concurrent Programming in Java: Design Principles and Patterns', 'Superseded by the second edition.', 'Doug Lea', '0201695812', 1996, 0),
    ('The Java Virtual Machine Specification', 'tIf you''re doing anything with the virtual machine, or if you just want to know what''s going on behind the scenes, then you need this book.', 'Tim Lindholm, Frank Yellin, Bill Joy, Kathy Walrath', '020163452X', 1996, 0),
    ('Java in a Nutshell: A Desktop Quick Reference for Java Programmers', 'An excellent introduction to Java for C programmers, an excellent reference for everyone, and a bargain at $19.95.', 'David Flanagan', '1565921836', 1996, 0),
    ('The Java AWT Reference', 'This large gem of a book is often overlooked in favor of the second volume of the The Java Class Libraries: An Annotated Reference. However in many respects this is the superior book.', 'John Zukowski', '1565922409', 1997, 0),
    ('The Java Language Specification', 'For experts only. This book is full of turgid paragraphs.', 'James Gosling , Bill Joy, Guy Steele', '0-201-63451-1', 1996, 0),
    ('Thinking in Java', 'Thinking in Java is the best introduction to Java for experienced programmers. Eckel is an expert on object oriented programming, and this expertise shows in the book.', 'Bruce Eckel', '0136597238', 1998, 0),
    ('Head First Java, 2nd Edition', 'The book teaches you how to write code by working on fun examples like games, quizzes, and fun little apps. You’ll learn about networking and OOP techniques all through repetition and fun practice work.', ' Kathy Sierra, Bert Bates', '0596009205', 2013, 0),
    ('Java: A Beginner`s Guide, Seventh Edition', 'Fully updated for Java Platform it gets you started programming in Java right away.', 'Herbert Schildt', '1259589317', 2017, 0),
    ('Java: The Complete Reference, Tenth Edition', 'Fully updated for Java SE 9 this book explains how to develop, compile, debug, and run Java programs.', 'Herbert Schildt', '1259589331', 2017, 0),
    ('Java 8 in Action: Lambdas, Streams, and functional-style programming', 'The book covers lambdas, streams, and functional-style programming.', 'Raoul-Gabriel Urma, Mario Fusco, Alan Mycroft', 'I1617291994', 2014, 0),
    ('Java SE8 for the Really Impatient: A Short Course on the Basics (Java Series)', 'This book specifically covers Java SE8 and the new features that come along with it. Lambda expressions, annotations, and JavaFX are all covered in detail along with many other facets of the language.', 'Cay S. Horstmann', '0321927761', 2014, 0),
    ('Beginning Programming with Java For Dummies (For Dummies (Computers)) 4th Edition', 'If you’re a new programmer, or want to be, this unintimidating guide gets you on your way toward Java mastery. It explores what goes into creating a program, how to put the pieces together, debugging, and making it all work.', 'Barry A. Burd', '1118407814', 2014, 0),
    ('Core Java Volume I--Fundamentals (10th Edition)', 'Core Java® has long been recognized as the leading, no-nonsense tutorial and reference for experienced programmers who want to write robust Java code for real-world applications.', 'Cay S. Horstmann', '0134177304', 2016, 0),
    ('Java in 24 Hours, Sams Teach Yourself (Covering Java 8) (7th Edition)', 'In just 24 lessons of one hour or less, you can learn the fundamentals of Java programming.', 'Rogers Cadenhead', '0672337029', 2014, 0),
    ('Learn Java in One Day and Learn It Well (Learn Coding Fast)', 'This book is for you. You no longer have to waste your time and money trying to learn Java from boring books that are 600 pages long, expensive online courses or complicated Java tutorials that just leave you more confused and frustrated.', 'Jamie Chan', '1539397831', 2016, 0),
    ('Murach`s Beginning Java with Eclipse', 'Its goal is to ease the steep learning curve and it uses the Eclipse IDE to make you productive as quickly as possible. In fact, you`ll grow from beginner to entry-level professional!', 'Joel Murach', '1890774898', 2015, 0),
    ('Java Programming: 24-Hour Trainer', 'This is your complete beginner`s guide to the Java programming language, with easy-to-follow lessons and supplemental exercises that help you get up and running quickly.', 'Yakov Fain', '111895145X', 2015, 0),
    ('Java Performance: The Definitive Guide: Getting the Most Out of Your Code', 'In this comprehensive guide, author and Java expert Scott Oaks takes the approach that anyone who works with Java should be equally adept at understanding how code behaves in the JVM, as well as the tunings likely to help its performance.', 'Scott Oaks', '1449358454', 2014, 0),
    ('Java Programming 9th Edition', 'With this dynamic text, even first-time programmers can quickly develop useful programs while mastering the basic principles of structured and object-oriented programming.', 'Joyce Farrell', '1337397075', 2018, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0),
    ('Name', 'description', 'Author', 'ISBN', 1996, 0);
